accumulate:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/a/accumu01.mp3
  audio_source: merriam-webster
  definition: collect, gather
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ə-ˈkyü-myə-ˌlāt
  pronunciation_source: merriam-webster
  word: accumulate
allowance:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/a/allowa03.mp3
  audio_source: merriam-webster
  definition: an amount of money given regularly for a specific purpose
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ə-ˈlau̇-əns
  pronunciation_source: merriam-webster
  word: allowance
appetite:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/a/appeti01.mp3
  audio_source: merriam-webster
  definition: a natural desire especially for food
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈa-pə-ˌtīt
  pronunciation_source: merriam-webster
  word: appetite
approach:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/a/approa01.mp3
  audio_source: merriam-webster
  definition: 'to come near or nearer : draw close'
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ə-ˈprōch
  pronunciation_source: merriam-webster
  word: approach
artistic:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/a/artist03.mp3
  audio_source: merriam-webster
  definition: relating to art or artists
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: är-ˈti-stik
  pronunciation_source: merriam-webster
  word: artistic
athleticism:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/a/athlet04.mp3
  audio_source: merriam-webster
  definition: of, relating to, or characteristic of athletes or athletics
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: ath-ˈle-tik
  pronunciation_source: merriam-webster
  word: athleticism
atomic:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/a/atomic01.mp3
  audio_source: merriam-webster
  definition: of or relating to atoms
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: ə-ˈtä-mik
  pronunciation_source: merriam-webster
  word: atomic
capitalism:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/c/capita02.mp3
  audio_source: merriam-webster
  definition: a system under which the ownership of land and wealth is for the most
    part in the hands of private individuals
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈka-pə-tə-ˌliz-əm
  pronunciation_source: merriam-webster
  word: capitalism
coincide:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/c/coinci02.mp3
  audio_source: merriam-webster
  definition: to happen at the same time
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ˌkō-ən-ˈsīd
  pronunciation_source: merriam-webster
  word: coincide
comic:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/c/comic001.mp3
  audio_source: merriam-webster
  definition: of, relating to, or characteristic of comedy
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: ˈkä-mik
  pronunciation_source: merriam-webster
  word: comic
committee:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/c/commit05.mp3
  audio_source: merriam-webster
  definition: a group of persons appointed or elected to study a problem, plan an
    event, or perform a specific duty
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: kə-ˈmi-tē
  pronunciation_source: merriam-webster
  word: committee
cowardice:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/c/coward02.mp3
  audio_source: merriam-webster
  definition: shameful fear
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈkau̇-ər-dəs
  pronunciation_source: merriam-webster
  word: cowardice
devastate:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/d/devast01.mp3
  audio_source: merriam-webster
  definition: to destroy entirely or nearly entirely
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ˈde-və-ˌstāt
  pronunciation_source: merriam-webster
  word: devastate
dramatic:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/d/dramat01.mp3
  audio_source: merriam-webster
  definition: having to do with drama
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: drə-ˈma-tik
  pronunciation_source: merriam-webster
  word: dramatic
elevate:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/e/elevat01.mp3
  audio_source: merriam-webster
  definition: 'to lift up : raise'
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ˈe-lə-ˌvāt
  pronunciation_source: merriam-webster
  word: elevate
embroider:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/e/embroi01.mp3
  audio_source: merriam-webster
  definition: to make with needlework
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: im-ˈbrȯi-dər
  pronunciation_source: merriam-webster
  word: embroider
endeavor:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/e/endeav01.mp3
  audio_source: merriam-webster
  definition: 'to make an effort : try hard'
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: in-ˈde-vər
  pronunciation_source: merriam-webster
  word: endeavor
eradicate:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/e/eradic01.mp3
  audio_source: merriam-webster
  definition: to destroy completely
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: i-ˈra-də-ˌkāt
  pronunciation_source: merriam-webster
  word: eradicate
evacuate:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/e/evacua01.mp3
  audio_source: merriam-webster
  definition: to leave or cause to leave a place of danger
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: i-ˈva-kyə-ˌwāt
  pronunciation_source: merriam-webster
  word: evacuate
evaporate:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/e/evapor01.mp3
  audio_source: merriam-webster
  definition: to change into vapor
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: i-ˈva-pə-ˌrāt
  pronunciation_source: merriam-webster
  word: evaporate
excavate:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/e/excava01.mp3
  audio_source: merriam-webster
  definition: to expose to view by digging away a covering
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ˈek-skə-ˌvāt
  pronunciation_source: merriam-webster
  word: excavate
executive:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/e/execut06.mp3
  audio_source: merriam-webster
  definition: fitted for or relating to the managing or directing of things
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: ig-ˈze-kyə-tiv
  pronunciation_source: merriam-webster
  word: executive
flounder:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/f/flound01.mp3
  audio_source: merriam-webster
  definition: a flatfish used for food
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈflau̇n-dər
  pronunciation_source: merriam-webster
  word: flounder
heroic:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/h/heroic01.mp3
  audio_source: merriam-webster
  definition: of or relating to heroism or heroes
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: hi-ˈrō-ik
  pronunciation_source: merriam-webster
  word: heroic
heroism:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/h/herois01.mp3
  audio_source: merriam-webster
  definition: behavior showing great courage especially for a noble purpose
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈher-ə-ˌwi-zəm
  pronunciation_source: merriam-webster
  word: heroism
historic:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/h/histor02.mp3
  audio_source: merriam-webster
  definition: famous in history
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: hi-ˈstȯr-ik
  pronunciation_source: merriam-webster
  word: historic
improvise:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/i/improv14.mp3
  audio_source: merriam-webster
  definition: to speak or perform without preparing ahead of time
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ˈim-prə-ˌvīz
  pronunciation_source: merriam-webster
  word: improvise
intervene:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/i/interv05.mp3
  audio_source: merriam-webster
  definition: to come or occur between events, places, or points of time
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ˌin-tər-ˈvēn
  pronunciation_source: merriam-webster
  word: intervene
kinetic:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/k/kineti01.mp3
  audio_source: merriam-webster
  definition: relating to the motions of objects and the forces associated with them
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: kə-ˈne-tik
  pronunciation_source: merriam-webster
  word: kinetic
liberate:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/l/libera11.mp3
  audio_source: merriam-webster
  definition: to set free
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ˈli-bə-ˌrāt
  pronunciation_source: merriam-webster
  word: liberate
marshmallow:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/m/marshm01.mp3
  audio_source: merriam-webster
  definition: a soft spongy sweet food made from corn syrup, sugar, and gelatin
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈmärsh-ˌme-lō
  pronunciation_source: merriam-webster
  word: marshmallow
narrative:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/n/narrat06.mp3
  audio_source: merriam-webster
  definition: something (as a story) that is told in full detail
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈner-ə-tiv
  pronunciation_source: merriam-webster
  word: narrative
nautical:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/n/nautic01.mp3
  audio_source: merriam-webster
  definition: of or relating to sailors, navigation, or ships
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: ˈnȯ-ti-kəl
  pronunciation_source: merriam-webster
  word: nautical
negotiate:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/n/negoti05.mp3
  audio_source: merriam-webster
  definition: to have a discussion with another in order to settle something
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ni-ˈgō-shē-ˌāt
  pronunciation_source: merriam-webster
  word: negotiate
obsolete:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/o/obsole04.mp3
  audio_source: merriam-webster
  definition: 'no longer in use : out-of-date'
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: ˌäb-sə-ˈlēt
  pronunciation_source: merriam-webster
  word: obsolete
organism:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/o/organi06.mp3
  audio_source: merriam-webster
  definition: a living thing made up of one or more cells and able to carry on the
    activities of life (as using energy, growing, or reproducing)
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈȯr-gə-ˌni-zəm
  pronunciation_source: merriam-webster
  word: organism
possessive:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/p/posses08.mp3
  audio_source: merriam-webster
  definition: being or belonging to the case of a noun or pronoun that shows possession
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: pə-ˈze-siv
  pronunciation_source: merriam-webster
  word: possessive
proclaim:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/p/procla01.mp3
  audio_source: merriam-webster
  definition: 'to announce publicly : declare'
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: prō-ˈklām
  pronunciation_source: merriam-webster
  word: proclaim
prosecute:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/p/prosec02.mp3
  audio_source: merriam-webster
  definition: to carry on a legal action against an accused person to prove his or
    her guilt
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: ˈprä-si-ˌkyüt
  pronunciation_source: merriam-webster
  word: prosecute
provoke:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/p/provok01.mp3
  audio_source: merriam-webster
  definition: to cause to become angry
  definition_source: merriam-webster
  part_of_speech: verb
  part_of_speech_source: merriam-webster
  pronunciation: prə-ˈvōk
  pronunciation_source: merriam-webster
  word: provoke
realism:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/r/realis01.mp3
  audio_source: merriam-webster
  definition: willingness to face facts or to give in to what is necessary
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈrē-ə-ˌli-zəm
  pronunciation_source: merriam-webster
  word: realism
realm:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/r/realm001.mp3
  audio_source: merriam-webster
  definition: kingdom
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈrelm
  pronunciation_source: merriam-webster
  word: realm
remote:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/r/remote01.mp3
  audio_source: merriam-webster
  definition: far off in place or time
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: ri-ˈmōt
  pronunciation_source: merriam-webster
  word: remote
royalty:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/r/royalt01.mp3
  audio_source: merriam-webster
  definition: the status or power of a king or queen or his or her family
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈrȯi-əl-tē
  pronunciation_source: merriam-webster
  word: royalty
schedule:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/s/schedu01.mp3
  audio_source: merriam-webster
  definition: a plan of things that need to be done and the times they will be done
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈske-jül
  pronunciation_source: merriam-webster
  word: schedule
scoundrel:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/s/scound01.mp3
  audio_source: merriam-webster
  definition: a mean or wicked person
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈskau̇n-drəl
  pronunciation_source: merriam-webster
  word: scoundrel
secretive:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/s/secret12.mp3
  audio_source: merriam-webster
  definition: tending to act in secret or keep secrets
  definition_source: merriam-webster
  part_of_speech: adjective
  part_of_speech_source: merriam-webster
  pronunciation: ˈsē-krə-tiv
  pronunciation_source: merriam-webster
  word: secretive
tourism:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/7/78/LL-Q1860_%28eng%29-Wodencafe-tourism.wav/LL-Q1860_%28eng%29-Wodencafe-tourism.wav.mp3
  audio_source: wiktapi
  definition: The act of travelling or sightseeing, particularly away from one's home.
  definition_source: wiktapi
  part_of_speech: null
  part_of_speech_source: null
  pronunciation: null
  pronunciation_source: null
  word: tourism
treachery:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/t/treach02.mp3
  audio_source: merriam-webster
  definition: the behavior of a person who betrays trust or faith
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈtre-chə-rē
  pronunciation_source: merriam-webster
  word: treachery
treasury:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/t/treasu09.mp3
  audio_source: merriam-webster
  definition: a place in which money and valuable objects are kept
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈtre-zhə-rē
  pronunciation_source: merriam-webster
  word: treasury
typhoon:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/t/typhoo01.mp3
  audio_source: merriam-webster
  definition: a tropical cyclone in the region of the Philippines or the China Sea
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: tī-ˈfün
  pronunciation_source: merriam-webster
  word: typhoon
zeal:
  audio: https://media.merriam-webster.com/audio/prons/en/us/mp3/z/zeal0001.mp3
  audio_source: merriam-webster
  definition: eager desire to get something done or see something succeed
  definition_source: merriam-webster
  part_of_speech: noun
  part_of_speech_source: merriam-webster
  pronunciation: ˈzēl
  pronunciation_source: merriam-webster
  word: zeal
