accumulate:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f7/En-us-accumulate.ogg/En-us-accumulate.ogg.mp3
  definition: Collected; accumulated.
  part_of_speech: adj
  pronunciation: null
  word: accumulate
allowance:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/c/ce/En-us-allowance.ogg/En-us-allowance.ogg.mp3
  definition: Permission; granting, conceding, or admitting.
  part_of_speech: noun
  pronunciation: null
  word: allowance
appetite:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1e/En-us-appetite.ogg/En-us-appetite.ogg.mp3
  definition: A desire to eat food or consume drinks.
  part_of_speech: noun
  pronunciation: null
  word: appetite
approach:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/1/16/En-us-approach.ogg/En-us-approach.ogg.mp3
  definition: An act of drawing near in place or time; an advancing or coming near.
  part_of_speech: noun
  pronunciation: null
  word: approach
artistic:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/6/6a/LL-Q1860_%28eng%29-Wodencafe-artistic.wav/LL-Q1860_%28eng%29-Wodencafe-artistic.wav.mp3
  definition: Having or revealing creative skill.
  part_of_speech: adj
  pronunciation: null
  word: artistic
athleticism:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/1/17/LL-Q1860_%28eng%29-TranqyPoo-athleticism.wav/LL-Q1860_%28eng%29-TranqyPoo-athleticism.wav.mp3
  definition: The state of being an athlete, or of taking part in athletic events.
  part_of_speech: noun
  pronunciation: null
  word: athleticism
atomic:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a0/En-us-atomic.ogg/En-us-atomic.ogg.mp3
  definition: Of or relating to atoms; composed of atoms; monatomic.
  part_of_speech: adj
  pronunciation: null
  word: atomic
capitalism:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/d/d6/LL-Q1860_%28eng%29-Vealhurl-capitalism.wav/LL-Q1860_%28eng%29-Vealhurl-capitalism.wav.mp3
  definition: A socio-economic system based on private ownership of resources, and
    capital and their exploitation for profit.
  part_of_speech: noun
  pronunciation: null
  word: capitalism
coincide:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/2/27/En-us-coincide.ogg/En-us-coincide.ogg.mp3
  definition: To occupy exactly the same space.
  part_of_speech: verb
  pronunciation: null
  word: coincide
comic:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/4/4c/En-us-comic.ogg/En-us-comic.ogg.mp3
  definition: Pertaining to comedy, as a literary genre.
  part_of_speech: adj
  pronunciation: null
  word: comic
committee:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/4/4a/En-us-committee.ogg/En-us-committee.ogg.mp3
  definition: A body of one or more persons convened for the accomplishment of some
    specific purpose, typically with formal protocols.
  part_of_speech: noun
  pronunciation: null
  word: committee
cowardice:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/0/0a/LL-Q1860_%28eng%29-Vealhurl-cowardice.wav/LL-Q1860_%28eng%29-Vealhurl-cowardice.wav.mp3
  definition: Lack of courage.
  part_of_speech: noun
  pronunciation: null
  word: cowardice
devastate:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a9/En-us-devastate.ogg/En-us-devastate.ogg.mp3
  definition: To ruin many or all things over a large area, such as most or all buildings
    of a city, or cities of a region, or trees of a forest.
  part_of_speech: verb
  pronunciation: null
  word: devastate
dramatic:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/1/14/En-us-dramatic.ogg/En-us-dramatic.ogg.mp3
  definition: Of or relating to the drama.
  part_of_speech: adj
  pronunciation: null
  word: dramatic
elevate:
  audio: null
  definition: Elevated, raised aloft.
  part_of_speech: adj
  pronunciation: null
  word: elevate
embroider:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f5/En-us-embroider.ogg/En-us-embroider.ogg.mp3
  definition: To stitch a decorative design on fabric with needle and thread of various
    colours.
  part_of_speech: verb
  pronunciation: null
  word: embroider
endeavor:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b7/En-us-endeavor.ogg/En-us-endeavor.ogg.mp3
  definition: A sincere attempt; a determined or assiduous effort towards a specific
    goal; assiduous or persistent activity.
  part_of_speech: noun
  pronunciation: null
  word: endeavor
eradicate:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/8/86/En-us-eradicate.ogg/En-us-eradicate.ogg.mp3
  definition: To pull up by the roots.
  part_of_speech: verb
  pronunciation: null
  word: eradicate
evacuate:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/0/0d/LL-Q1860_%28eng%29-M%C3%A9lange_a_trois-evacuate.wav/LL-Q1860_%28eng%29-M%C3%A9lange_a_trois-evacuate.wav.mp3
  definition: To leave or withdraw from; to quit; to retire from.
  part_of_speech: verb
  pronunciation: null
  word: evacuate
evaporate:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/6/6b/En-us-evaporate.ogg/En-us-evaporate.ogg.mp3
  definition: evaporated
  part_of_speech: adj
  pronunciation: null
  word: evaporate
excavate:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/7/70/LL-Q1860_%28eng%29-Vealhurl-excavate.wav/LL-Q1860_%28eng%29-Vealhurl-excavate.wav.mp3
  definition: Made hollow.
  part_of_speech: adj
  pronunciation: null
  word: excavate
executive:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/3/3e/En-us-executive.ogg/En-us-executive.ogg.mp3
  definition: Designed or fitted for execution, or carrying into effect.
  part_of_speech: adj
  pronunciation: null
  word: executive
flounder:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/3/36/En-us-flounder.ogg/En-us-flounder.ogg.mp3
  definition: A European species of flatfish having dull brown colouring with reddish-brown
    blotches; fluke, European flounder (Platichthys flesus).
  part_of_speech: noun
  pronunciation: null
  word: flounder
heroic:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1a/En-us-heroic.ogg/En-us-heroic.ogg.mp3
  definition: Of or relating to a hero or heroine; supremely noble.
  part_of_speech: adj
  pronunciation: null
  word: heroic
heroism:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b8/En-us-heroism.ogg/En-us-heroism.ogg.mp3
  definition: The qualities characteristic of a hero, such as courage, bravery, fortitude,
    selflessness, etc.; the display of such qualities.
  part_of_speech: noun
  pronunciation: null
  word: heroism
historic:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1b/En-us-historic.ogg/En-us-historic.ogg.mp3
  definition: 'Very important; noteworthy: having importance or significance in history.'
  part_of_speech: adj
  pronunciation: null
  word: historic
improvise:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/9/9d/En-us-improvise.ogg/En-us-improvise.ogg.mp3
  definition: To make something up or invent it as one goes on; to proceed guided
    only by imagination, intuition, and guesswork rather than by a careful plan.
  part_of_speech: verb
  pronunciation: null
  word: improvise
intervene:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c5/LL-Q1860_%28eng%29-Vealhurl-intervene.wav/LL-Q1860_%28eng%29-Vealhurl-intervene.wav.mp3
  definition: To become involved in a situation, so as to alter or prevent an action.
  part_of_speech: verb
  pronunciation: null
  word: intervene
kinetic:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b5/LL-Q1860_%28eng%29-Tesco250-kinetic.wav/LL-Q1860_%28eng%29-Tesco250-kinetic.wav.mp3
  definition: Relating to motion.
  part_of_speech: adj
  pronunciation: null
  word: kinetic
liberate:
  audio: null
  definition: Freed, released; free.
  part_of_speech: adj
  pronunciation: null
  word: liberate
marshmallow:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/5/5d/En-us-marshmallow.ogg/En-us-marshmallow.ogg.mp3
  definition: Marsh mallow, a species of mallow, Althaea officinalis, that grows in
    marshy terrain.
  part_of_speech: noun
  pronunciation: null
  word: marshmallow
narrative:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a0/En-us-narrative.ogg/En-us-narrative.ogg.mp3
  definition: Telling a story.
  part_of_speech: adj
  pronunciation: null
  word: narrative
nautical:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/c/cd/En-us-nautical.ogg/En-us-nautical.ogg.mp3
  definition: Of, relating to, or characteristic of sailing, sailors, or the sea.
  part_of_speech: adj
  pronunciation: null
  word: nautical
negotiate:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2f/En-us-negotiate.ogg/En-us-negotiate.ogg.mp3
  definition: To confer with others in order to come to terms or reach an agreement.
  part_of_speech: verb
  pronunciation: null
  word: negotiate
obsolete:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1e/En-us-obsolete.ogg/En-us-obsolete.ogg.mp3
  definition: No longer in use or no longer useful; now disused or neglected (often
    in favour of something newer, better, or more fashionable); outmoded.
  part_of_speech: adj
  pronunciation: null
  word: obsolete
organism:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/8/85/En-us-organism.ogg/En-us-organism.ogg.mp3
  definition: A discrete and complete living thing, such as animal, plant, fungus
    or microorganism.
  part_of_speech: noun
  pronunciation: null
  word: organism
possessive:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e4/LL-Q1860_%28eng%29-Vealhurl-possessive.wav/LL-Q1860_%28eng%29-Vealhurl-possessive.wav.mp3
  definition: Of or pertaining to ownership or possession.
  part_of_speech: adj
  pronunciation: null
  word: possessive
proclaim:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/7/7e/LL-Q1860_%28eng%29-Vealhurl-proclaim.wav/LL-Q1860_%28eng%29-Vealhurl-proclaim.wav.mp3
  definition: To announce or declare.
  part_of_speech: verb
  pronunciation: null
  word: proclaim
prosecute:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/0/09/LL-Q1860_%28eng%29-Vealhurl-prosecute.wav/LL-Q1860_%28eng%29-Vealhurl-prosecute.wav.mp3
  definition: To start criminal proceedings against.
  part_of_speech: verb
  pronunciation: null
  word: prosecute
provoke:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1e/En-us-provoke.ogg/En-us-provoke.ogg.mp3
  definition: To cause someone to become annoyed or angry.
  part_of_speech: verb
  pronunciation: null
  word: provoke
realism:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/3/3d/LL-Q1860_%28eng%29-Wodencafe-realism.wav/LL-Q1860_%28eng%29-Wodencafe-realism.wav.mp3
  definition: A concern for fact or reality and rejection of the impractical and visionary.
  part_of_speech: noun
  pronunciation: null
  word: realism
realm:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a3/En-us-realm.ogg/En-us-realm.ogg.mp3
  definition: A territory or state, as ruled by an absolute authority, especially
    by a king; a kingdom.
  part_of_speech: noun
  pronunciation: null
  word: realm
remote:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/5/5a/En-us-remote.ogg/En-us-remote.ogg.mp3
  definition: At a distance; disconnected.
  part_of_speech: adj
  pronunciation: null
  word: remote
royalty:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2a/En-us-royalty.ogg/En-us-royalty.ogg.mp3
  definition: The rank, status, power or authority of a monarch.
  part_of_speech: noun
  pronunciation: null
  word: royalty
schedule:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/1/14/En-us-schedule.ogg/En-us-schedule.ogg.mp3
  definition: A procedural plan, usually but not necessarily tabular in nature, indicating
    a sequence of operations and the planned times at which those operations are to
    occur.
  part_of_speech: noun
  pronunciation: null
  word: schedule
scoundrel:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/e/ec/LL-Q1860_%28eng%29-Vealhurl-scoundrel.wav/LL-Q1860_%28eng%29-Vealhurl-scoundrel.wav.mp3
  definition: A mean, worthless fellow; a rascal; a villain; a person without honor
    or virtue.
  part_of_speech: noun
  pronunciation: null
  word: scoundrel
secretive:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/6/63/LL-Q1860_%28eng%29-Vealhurl-secretive1.wav/LL-Q1860_%28eng%29-Vealhurl-secretive1.wav.mp3
  definition: Having an inclination to secrecy.
  part_of_speech: adj
  pronunciation: null
  word: secretive
tourism:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/7/78/LL-Q1860_%28eng%29-Wodencafe-tourism.wav/LL-Q1860_%28eng%29-Wodencafe-tourism.wav.mp3
  definition: The act of travelling or sightseeing, particularly away from one's home.
  part_of_speech: noun
  pronunciation: null
  word: tourism
treachery:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/f/f6/LL-Q1860_%28eng%29-Vealhurl-treachery.wav/LL-Q1860_%28eng%29-Vealhurl-treachery.wav.mp3
  definition: Deliberate, often calculated, disregard for trust or faith.
  part_of_speech: noun
  pronunciation: null
  word: treachery
treasury:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/5/53/En-us-treasury.ogg/En-us-treasury.ogg.mp3
  definition: A place where treasure is stored safely.
  part_of_speech: noun
  pronunciation: null
  word: treasury
typhoon:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/2/24/En-us-typhoon.ogg/En-us-typhoon.ogg.mp3
  definition: A severe tropical cyclone; an intense, rotating storm.
  part_of_speech: noun
  pronunciation: null
  word: typhoon
zeal:
  audio: https://upload.wikimedia.org/wikipedia/commons/transcoded/f/fd/En-us-zeal.ogg/En-us-zeal.ogg.mp3
  definition: The fervour or tireless devotion for a person, cause, or ideal and determination
    in its furtherance; diligent enthusiasm; powerful interest.
  part_of_speech: noun
  pronunciation: null
  word: zeal
